# site properties and page defaults
title: AGN Lab
subtitle: 
description: AGN Lab focuses on studying Active Galactic Nuclei (AGN), exploring their emission mechanisms, variability, and impact on their host galaxies. The lab utilizes multi-wavelength observations and theoretical modeling to understand the physical processes driving AGN activity. Through collaborative research, AGN Lab aims to contribute to advancements in astrophysics and our understanding of the universe.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: priraj@bhu.ac.in
  orcid: 0000-0002-1173-7310
  google-scholar: bbqblCkAAAAJ
  github: joysankar0701
  twitter: none
  youtube: none

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
